"""baseline schema

Revision ID: 80bac37d379c
Revises: 
Create Date: 2025-11-28 13:41:51.524848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80bac37d379c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_parent_id', table_name='book_categories')
    op.drop_table('book_categories')
    op.drop_index('idx_courier_id', table_name='delivery_tasks')
    op.drop_index('idx_created_at', table_name='delivery_tasks')
    op.drop_index('idx_delivery_tasks_composite', table_name='delivery_tasks')
    op.drop_index('idx_order_id', table_name='delivery_tasks')
    op.drop_index('idx_status', table_name='delivery_tasks')
    op.drop_table('delivery_tasks')
    op.drop_index('idx_last_message_at', table_name='chat_sessions')
    op.drop_index('idx_user1_id', table_name='chat_sessions')
    op.drop_index('idx_user2_id', table_name='chat_sessions')
    op.drop_index('unique_user_pair', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('idx_is_online', table_name='couriers')
    op.drop_index('idx_status', table_name='couriers')
    op.drop_index('unique_user_id', table_name='couriers')
    op.drop_table('couriers')
    op.drop_index('idx_book_id', table_name='favorites')
    op.drop_index('idx_user_id', table_name='favorites')
    op.drop_index('unique_user_book', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('idx_is_active', table_name='announcements')
    op.drop_index('idx_is_pinned', table_name='announcements')
    op.drop_index('idx_publish_at', table_name='announcements')
    op.drop_table('announcements')
    op.drop_index('idx_books_search', table_name='books')
    op.drop_index('idx_category_id', table_name='books')
    op.drop_index('idx_created_at', table_name='books')
    op.drop_index('idx_isbn', table_name='books')
    op.drop_index('idx_price', table_name='books')
    op.drop_index('idx_seller_id', table_name='books')
    op.drop_index('idx_status', table_name='books')
    op.drop_table('books')
    op.drop_index('email', table_name='users')
    op.drop_index('idx_credit_score', table_name='users')
    op.drop_index('idx_phone', table_name='users')
    op.drop_index('idx_student_id', table_name='users')
    op.drop_index('student_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_created_at', table_name='chat_messages')
    op.drop_index('idx_sender_id', table_name='chat_messages')
    op.drop_index('idx_session_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_buyer_id', table_name='orders')
    op.drop_index('idx_created_at', table_name='orders')
    op.drop_index('idx_order_number', table_name='orders')
    op.drop_index('idx_orders_composite', table_name='orders')
    op.drop_index('idx_seller_id', table_name='orders')
    op.drop_index('idx_status', table_name='orders')
    op.drop_index('order_number', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_book_id', table_name='book_images')
    op.drop_table('book_images')
    op.drop_index('idx_created_at', table_name='reviews')
    op.drop_index('idx_rating', table_name='reviews')
    op.drop_index('idx_reviewed_id', table_name='reviews')
    op.drop_index('unique_order_reviewer', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text('(uuid())'), nullable=False),
    sa.Column('order_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='订单ID'),
    sa.Column('reviewer_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='评价人ID'),
    sa.Column('reviewed_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='被评价人ID'),
    sa.Column('role', mysql.ENUM('buyer', 'seller', 'courier'), nullable=False, comment='评价角色'),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=False, comment='评分1-5'),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='评价内容'),
    sa.Column('tags', mysql.JSON(), nullable=True, comment='评价标签'),
    sa.Column('is_anonymous', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否匿名'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('((`rating` >= 1) and (`rating` <= 5))', name='reviews_chk_1'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='reviews_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_id'], ['users.id'], name='reviews_ibfk_3'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name='reviews_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    comment='评价表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='评价表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_order_reviewer', 'reviews', ['order_id', 'reviewer_id', 'role'], unique=True)
    op.create_index('idx_reviewed_id', 'reviews', ['reviewed_id'], unique=False)
    op.create_index('idx_rating', 'reviews', ['rating'], unique=False)
    op.create_index('idx_created_at', 'reviews', ['created_at'], unique=False)
    op.create_table('book_images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='书籍ID'),
    sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False, comment='图片URL'),
    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_primary', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否主图'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='book_images_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='书籍图片表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='书籍图片表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_book_id', 'book_images', ['book_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text('(uuid())'), nullable=False),
    sa.Column('order_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='订单编号'),
    sa.Column('book_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='书籍ID'),
    sa.Column('buyer_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='买家ID'),
    sa.Column('seller_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='卖家ID'),
    sa.Column('book_price', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='书籍价格'),
    sa.Column('delivery_fee', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True, comment='配送费'),
    sa.Column('total_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='总金额'),
    sa.Column('status', mysql.ENUM('pending', 'confirmed', 'paid', 'shipping', 'completed', 'cancelled', 'refunded'), server_default=sa.text("'pending'"), nullable=True, comment='订单状态'),
    sa.Column('delivery_method', mysql.ENUM('meetup', 'delivery'), nullable=False, comment='配送方式'),
    sa.Column('meetup_location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='见面地点'),
    sa.Column('meetup_time', mysql.TIMESTAMP(), nullable=True, comment='见面时间'),
    sa.Column('payment_method', mysql.ENUM('wechat', 'alipay', 'cash'), nullable=True, comment='支付方式'),
    sa.Column('payment_status', mysql.ENUM('pending', 'paid', 'failed', 'refunded'), server_default=sa.text("'pending'"), nullable=True, comment='支付状态'),
    sa.Column('paid_at', mysql.TIMESTAMP(), nullable=True, comment='支付时间'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('completed_at', mysql.TIMESTAMP(), nullable=True, comment='完成时间'),
    sa.Column('cancelled_at', mysql.TIMESTAMP(), nullable=True, comment='取消时间'),
    sa.Column('pickup_location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('delivery_location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('payment_due_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='orders_ibfk_1'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='orders_ibfk_2'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name='orders_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    comment='订单表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='订单表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('order_number', 'orders', ['order_number'], unique=True)
    op.create_index('idx_status', 'orders', ['status'], unique=False)
    op.create_index('idx_seller_id', 'orders', ['seller_id'], unique=False)
    op.create_index('idx_orders_composite', 'orders', ['buyer_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_order_number', 'orders', ['order_number'], unique=False)
    op.create_index('idx_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('idx_buyer_id', 'orders', ['buyer_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text('(uuid())'), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='会话ID'),
    sa.Column('sender_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='发送者ID'),
    sa.Column('message_type', mysql.ENUM('text', 'image', 'system'), server_default=sa.text("'text'"), nullable=True, comment='消息类型'),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='消息内容'),
    sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='图片URL'),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否已读'),
    sa.Column('read_at', mysql.TIMESTAMP(), nullable=True, comment='阅读时间'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='chat_messages_ibfk_2'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name='chat_messages_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='聊天消息表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='聊天消息表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_index('idx_sender_id', 'chat_messages', ['sender_id'], unique=False)
    op.create_index('idx_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text('(uuid())'), nullable=False),
    sa.Column('student_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False, comment='学号'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='姓名'),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False, comment='手机号'),
    sa.Column('avatar_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='头像URL'),
    sa.Column('hashed_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True, comment='密码哈希'),
    sa.Column('credit_score', mysql.INTEGER(), server_default=sa.text("'100'"), autoincrement=False, nullable=True, comment='信用分，初始100分'),
    sa.Column('total_transactions', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='总交易次数'),
    sa.Column('positive_reviews', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='好评数'),
    sa.Column('negative_reviews', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='差评数'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='是否激活'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='用户表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('student_id', 'users', ['student_id'], unique=True)
    op.create_index('idx_student_id', 'users', ['student_id'], unique=False)
    op.create_index('idx_phone', 'users', ['phone'], unique=False)
    op.create_index('idx_credit_score', 'users', ['credit_score'], unique=False)
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_table('books',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text('(uuid())'), nullable=False),
    sa.Column('isbn', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False, comment='ISBN号'),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False, comment='书名'),
    sa.Column('author', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='作者'),
    sa.Column('publisher', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='出版社'),
    sa.Column('publish_date', sa.DATE(), nullable=True, comment='出版日期'),
    sa.Column('edition', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='版次'),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='分类ID'),
    sa.Column('cover_image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='封面图片'),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='书籍描述'),
    sa.Column('original_price', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='原价'),
    sa.Column('selling_price', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='售价'),
    sa.Column('condition_level', mysql.ENUM('excellent', 'good', 'fair', 'poor'), nullable=False, comment='品相等级'),
    sa.Column('condition_description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='品相详细描述'),
    sa.Column('seller_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='卖家ID'),
    sa.Column('status', mysql.ENUM('available', 'reserved', 'sold', 'off_shelf'), server_default=sa.text("'available'"), nullable=True, comment='书籍状态'),
    sa.Column('view_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='浏览数'),
    sa.Column('favorite_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='收藏数'),
    sa.Column('is_approved', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否审核通过'),
    sa.Column('approved_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=True, comment='审核人'),
    sa.Column('approved_at', mysql.TIMESTAMP(), nullable=True, comment='审核时间'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('publish_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gallery_images', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='books_ibfk_3'),
    sa.ForeignKeyConstraint(['category_id'], ['book_categories.id'], name='books_ibfk_2'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name='books_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='书籍信息表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='书籍信息表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_status', 'books', ['status'], unique=False)
    op.create_index('idx_seller_id', 'books', ['seller_id'], unique=False)
    op.create_index('idx_price', 'books', ['selling_price'], unique=False)
    op.create_index('idx_isbn', 'books', ['isbn'], unique=False)
    op.create_index('idx_created_at', 'books', ['created_at'], unique=False)
    op.create_index('idx_category_id', 'books', ['category_id'], unique=False)
    op.create_index('idx_books_search', 'books', ['title', 'author', 'publisher'], unique=False)
    op.create_table('announcements',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False, comment='公告标题'),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='公告内容'),
    sa.Column('author_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='发布人ID'),
    sa.Column('is_pinned', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否置顶'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='是否有效'),
    sa.Column('publish_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='发布时间'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='announcements_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统公告表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='系统公告表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_publish_at', 'announcements', ['publish_at'], unique=False)
    op.create_index('idx_is_pinned', 'announcements', ['is_pinned'], unique=False)
    op.create_index('idx_is_active', 'announcements', ['is_active'], unique=False)
    op.create_table('favorites',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='用户ID'),
    sa.Column('book_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='书籍ID'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='favorites_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorites_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='收藏表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='收藏表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_user_book', 'favorites', ['user_id', 'book_id'], unique=True)
    op.create_index('idx_user_id', 'favorites', ['user_id'], unique=False)
    op.create_index('idx_book_id', 'favorites', ['book_id'], unique=False)
    op.create_table('couriers',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text('(uuid())'), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='用户ID'),
    sa.Column('id_card_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False, comment='身份证号'),
    sa.Column('id_card_front', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='身份证正面'),
    sa.Column('id_card_back', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='身份证反面'),
    sa.Column('student_card', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='学生证照片'),
    sa.Column('status', mysql.ENUM('pending', 'approved', 'rejected', 'suspended'), server_default=sa.text("'pending'"), nullable=True, comment='审核状态'),
    sa.Column('total_orders', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='总接单数'),
    sa.Column('completed_orders', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='完成订单数'),
    sa.Column('rating', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text("'5.00'"), nullable=True, comment='评分'),
    sa.Column('is_online', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否在线接单'),
    sa.Column('last_online_time', mysql.TIMESTAMP(), nullable=True, comment='最后上线时间'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='couriers_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='众包配送员表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='众包配送员表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_user_id', 'couriers', ['user_id'], unique=True)
    op.create_index('idx_status', 'couriers', ['status'], unique=False)
    op.create_index('idx_is_online', 'couriers', ['is_online'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text('(uuid())'), nullable=False),
    sa.Column('user1_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='用户1ID'),
    sa.Column('user2_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='用户2ID'),
    sa.Column('book_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=True, comment='关联书籍ID'),
    sa.Column('last_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='最后一条消息'),
    sa.Column('last_message_at', mysql.TIMESTAMP(), nullable=True, comment='最后消息时间'),
    sa.Column('unread_count_user1', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='用户1未读消息数'),
    sa.Column('unread_count_user2', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='用户2未读消息数'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='chat_sessions_ibfk_3'),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], name='chat_sessions_ibfk_1'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], name='chat_sessions_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    comment='聊天会话表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='聊天会话表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_user_pair', 'chat_sessions', ['user1_id', 'user2_id', 'book_id'], unique=True)
    op.create_index('idx_user2_id', 'chat_sessions', ['user2_id'], unique=False)
    op.create_index('idx_user1_id', 'chat_sessions', ['user1_id'], unique=False)
    op.create_index('idx_last_message_at', 'chat_sessions', ['last_message_at'], unique=False)
    op.create_table('delivery_tasks',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), server_default=sa.text('(uuid())'), nullable=False),
    sa.Column('order_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='订单ID'),
    sa.Column('courier_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=True, comment='配送员ID'),
    sa.Column('pickup_location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False, comment='取书地点'),
    sa.Column('delivery_location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False, comment='送书地点'),
    sa.Column('delivery_fee', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='配送费'),
    sa.Column('status', mysql.ENUM('pending', 'accepted', 'picked_up', 'delivering', 'delivered', 'cancelled'), server_default=sa.text("'pending'"), nullable=True, comment='配送状态'),
    sa.Column('estimated_duration', mysql.INTEGER(), autoincrement=False, nullable=True, comment='预计时长(分钟)'),
    sa.Column('actual_duration', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际时长(分钟)'),
    sa.Column('pickup_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True, comment='取书码'),
    sa.Column('delivery_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True, comment='送达码'),
    sa.Column('accepted_at', mysql.TIMESTAMP(), nullable=True, comment='接单时间'),
    sa.Column('picked_up_at', mysql.TIMESTAMP(), nullable=True, comment='取书时间'),
    sa.Column('delivered_at', mysql.TIMESTAMP(), nullable=True, comment='送达时间'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], name='delivery_tasks_ibfk_2'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='delivery_tasks_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='配送任务表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='配送任务表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_status', 'delivery_tasks', ['status'], unique=False)
    op.create_index('idx_order_id', 'delivery_tasks', ['order_id'], unique=False)
    op.create_index('idx_delivery_tasks_composite', 'delivery_tasks', ['status', 'created_at'], unique=False)
    op.create_index('idx_created_at', 'delivery_tasks', ['created_at'], unique=False)
    op.create_index('idx_courier_id', 'delivery_tasks', ['courier_id'], unique=False)
    op.create_table('book_categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='分类名称'),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='分类描述'),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='父分类ID'),
    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='是否启用'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['book_categories.id'], name='book_categories_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    comment='书籍分类表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='书籍分类表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_parent_id', 'book_categories', ['parent_id'], unique=False)
    # ### end Alembic commands ###
